sudo: false
language: node_js
node_js:
  - '10'
  - '11'
# keep the npm cache to speed up installs
cache:
  directories:
    - '$HOME/.npm'
install:
  - npm install
script:
  - npm run build
  - npm run test
notifications:
  email: false
