version: '3.4'

services:
  mongodb:
    image: postgres:latest
    env_file:
      - ../.env.example
    ports:
      - "5432:5432"
    container_name: ts-node-pg
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:

networks:
  default:
    driver: bridge

