FORMAT: 1A
HOST: https://localhost:3000

# ts-node starter
Example REST API written in [Marble.js](http://marblejs.com) framework.

For implementation details you can visit the following link: [ts-node-starter](https://github.com/theodesp/ts-node-starter)

### Get version [GET]

Retrieve information about API availability

+ Response 200 (text/plain)

        "v1"

:[Auth](./auth/auth.api.apib)
:[Users](./users/users.api.apib)
:[Health](./health/health.api.apib)
