# Group Health

Generic Health Endpoint to check system liveness

## Health [/health]

### Show health status [GET]

+ Response 200 (application/json)

        {
            "message": "Hello world!"
        }
